start_date = '2014-12-31'
end_date = '2017-01-01'











universe = [
    "A", "AAL", "AAP", "AAPL", "ABT", "ACN", "ADBE", "ADI", "ADM", "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG",
    "AIZ", "AJG", "AKAM", "ALB", "ALGN", "ALK", "ALL", "AMAT", "AMD", "AME", "AMGN", "AMP", "AMT", "AMZN", "ANSS",
    "AON", "AOS", "APA", "APD", "APH", "ARE", "ATO", "AVB", "AVY", "AXP", "AZO", "BA", "BAC", "BAX", "BBY", "BDX",
    "BEN", "BIIB", "BIO", "BK", "BKNG", "BKR", "BLK", "BMY", "BSX", "BWA", "BXP", "C", "CAG", "CAH", "CAT", "CB",
    "CBRE", "CCI", "CCL", "CDNS", "CE", "CF", "CHD", "CHRW", "CI", "CINF", "CL", "CLX", "CMA", "CMCSA", "CME", "CMI",
    "CMS", "CNC", "CNP", "COF", "COO", "COP", "COST", "CPB", "CPRT", "CRM", "CSCO", "CSX", "CTAS", "CTSH", "CVS",
    "CVX", "D", "DD", "DE", "DGX", "DHI", "DHR", "DLR", "DLTR", "DOV", "DPZ", "DRI", "DTE", "DUK", "DVA", "DVN",
    "DXC", "DXCM", "EA", "EBAY", "ECL", "ED", "EFX", "EIX", "EL", "EMN", "EMR", "EOG", "EQIX", "EQR", "ES", "ESS",
    "ETN", "ETR", "EVRG", "EW", "EXC", "EXPD", "EXPE", "EXR", "F", "FAST", "FCX", "FDX", "FE", "FFIV", "FIS", "FITB",
    "FMC", "FRT", "GD", "GE", "GILD", "GIS", "GL", "GLW", "GOOG", "GOOGL", "GPC", "GPN", "GRMN", "GS", "GWW", "HAL",
    "HAS", "HBAN", "HD", "HES", "HIG", "HOLX", "HON", "HPQ", "HRL", "HSIC", "HST", "HSY", "HUM", "IBM", "ICE",
    "IDXX", "IEX", "IFF", "ILMN", "INCY", "INTC", "INTU", "IP", "IPG", "IRM", "ISRG", "IT", "ITW", "IVZ", "J",
    "JBHT", "JCI", "JKHY", "JNJ", "JNPR", "JPM", "K", "KEY", "KIM", "KLAC", "KMB", "KMX", "KO", "KR", "L", "LEG",
    "LEN", "LH", "LHX", "LIN", "LKQ", "LLY", "LMT", "LNC", "LNT", "LOW", "LRCX", "LUV", "LVS", "LYV", "MAA", "MAR",
    "MAS", "MCD", "MCHP", "MCK", "MCO", "MDLZ", "MDT", "MET", "MGM", "MHK", "MKC", "MKTX", "MLM", "MMC", "MMM",
    "MNST", "MO", "MOS", "MPWR", "MRK", "MS", "MSFT", "MSI", "MTB", "MTD", "MU", "NDAQ", "NEE", "NEM", "NFLX", "NI",
    "NKE", "NOC", "NOV", "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA", "NVR", "NWL", "O", "ODFL", "OKE", "OMC",
    "ORCL", "ORLY", "OXY", "PAYX", "PCAR", "PEG", "PENN", "PEP", "PFE", "PFG", "PG", "PGR", "PH", "PHM", "PKG",
    "PLD", "PNC", "PNR", "PNW", "POOL", "PPG", "PPL", "PRGO", "PRU", "PSA", "PVH", "PWR", "QCOM", "REG", "REGN",
    "RF", "RHI", "RJF", "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG", "RTX", "SBAC", "SBUX", "SCHW", "SEE", "SHW",
    "SJM", "SLB", "SNA", "SNPS", "SO", "SPG", "SPGI",  "SRE", "STE", "STT", "STX", "STZ", "SWK", "SWKS", "SYK",
    "SYY", "T", "TAP", "TDY", "TER", "TFC", "TFX", "TGT", "TJX", "TMO", "TPR", "TRMB", "TROW", "TRV", "TSCO", "TSN",
    "TT", "TTWO", "TXN", "TXT", "TYL", "UAA", "UDR", "UHS", "UNH", "UNM", "UNP", "UPS", "URI", "USB", "VFC", "VLO",
    "VMC", "VNO", "VRSN", "VRTX", "VTR", "VTRS", "VZ", "WAB", "WAT", "WBA", "WDC", "WEC", "WELL", "WFC", "WHR",
    "WM", "WMB", "WMT", "WRB", "WST", "WY", "WYNN", "XEL", "XOM", "XRAY", "YUM", "ZBH", "ZBRA", "ZION"
]


sp500b = "A AAL AAP AAPL ABT ACN ADBE ADI ADM ADP ADSK AEE AEP AES AFL AIG AIZ AJG AKAM ALB ALGN ALK ALL AMAT AMD AME AMGN AMP AMT AMZN ANSS AON AOS APA APD APH ARE ATO AVB AVY AXP AZO BA BAC BAX BBY BDX BEN BIIB BIO BK BKNG BKR BLK BMY BSX BWA BXP C CAG CAH CAT CB CBRE CCI CCL CDNS CE CF CHD CHRW CI CINF CL CLX CMA CMCSA CME CMI CMS CNC CNP COF COO COP COST CPB CPRT CRM CSCO CSX CTAS CTSH CVS CVX D DD DE DGX DHI DHR DLR DLTR DOV DPZ DRI DTE DUK DVA DVN DXC DXCM EA EBAY ECL ED EFX EIX EL EMN EMR EOG EQIX EQR ES ESS ETN ETR EVRG EW EXC EXPD EXPE EXR F FAST FCX FDX FE FFIV FIS FITB FMC FRT GD GE GILD GIS GL GLW GOOG GOOGL GPC GPN GRMN GS GWW HAL HAS HBAN HD HES HIG HOLX HON HPQ HRL HSIC HST HSY HUM IBM ICE IDXX IEX IFF ILMN INCY INTC INTU IP IPG IRM ISRG IT ITW IVZ J JBHT JCI JKHY JNJ JNPR JPM K KEY KIM KLAC KMB KMX KO KR L LEG LEN LH LHX LIN LKQ LLY LMT LNC LNT LOW LRCX LUV LVS LYV MAA MAR MAS MCD MCHP MCK MCO MDLZ MDT MET MGM MHK MKC MKTX MLM MMC MMM MNST MO MOS MPWR MRK MS MSFT MSI MTB MTD MU NDAQ NEE NEM NFLX NI NKE NOC NOV NRG NSC NTAP NTRS NUE NVDA NVR NWL O ODFL OKE OMC ORCL ORLY OXY PAYX PCAR PEG PENN PEP PFE PFG PG PGR PH PHM PKG PLD PNC PNR PNW POOL PPG PPL PRGO PRU PSA PVH PWR QCOM REG REGN RF RHI RJF RL RMD ROK ROL ROP ROST RSG RTX SBAC SBUX SCHW SEE SHW SJM SLB SNA SNPS SO SPG SPGI SPY SRE STE STT STX STZ SWK SWKS SYK SYY T TAP TDY TER TFC TFX TGT TJX TMO TPR TRMB TROW TRV TSCO TSN TT TTWO TXN TXT TYL UAA UDR UHS UNH UNM UNP UPS URI USB VFC VLO VMC VNO VRSN VRTX VTR VTRS VZ WAB WAT WBA WDC WEC WELL WFC WHR WM WMB WMT WRB WST WY WYNN XEL XOM XRAY YUM ZBH ZBRA ZION"

